[package]
name = "actixhtmx"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
askama = "0.12.1"
env_logger = "0.11.6"
log = "0.4.22"
serde = "1.0.217"

[package.metadata.scripts]
start = "cargo watch -x 'run' -w src -w templates -w static"
